/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RehabilitationServicesRouteImport } from './routes/rehabilitation-services'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RehabilitationServicesSlugRouteImport } from './routes/rehabilitation-services.$slug'
import { Route as ConditionsSlugRouteImport } from './routes/conditions.$slug'

const RehabilitationServicesRoute = RehabilitationServicesRouteImport.update({
  id: '/rehabilitation-services',
  path: '/rehabilitation-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RehabilitationServicesSlugRoute =
  RehabilitationServicesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => RehabilitationServicesRoute,
  } as any)
const ConditionsSlugRoute = ConditionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConditionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conditions': typeof ConditionsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/rehabilitation-services': typeof RehabilitationServicesRouteWithChildren
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/rehabilitation-services/$slug': typeof RehabilitationServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conditions': typeof ConditionsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/rehabilitation-services': typeof RehabilitationServicesRouteWithChildren
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/rehabilitation-services/$slug': typeof RehabilitationServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conditions': typeof ConditionsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/rehabilitation-services': typeof RehabilitationServicesRouteWithChildren
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/rehabilitation-services/$slug': typeof RehabilitationServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/conditions'
    | '/programs'
    | '/rehabilitation-services'
    | '/conditions/$slug'
    | '/rehabilitation-services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/conditions'
    | '/programs'
    | '/rehabilitation-services'
    | '/conditions/$slug'
    | '/rehabilitation-services/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/conditions'
    | '/programs'
    | '/rehabilitation-services'
    | '/conditions/$slug'
    | '/rehabilitation-services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConditionsRoute: typeof ConditionsRouteWithChildren
  ProgramsRoute: typeof ProgramsRoute
  RehabilitationServicesRoute: typeof RehabilitationServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rehabilitation-services': {
      id: '/rehabilitation-services'
      path: '/rehabilitation-services'
      fullPath: '/rehabilitation-services'
      preLoaderRoute: typeof RehabilitationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rehabilitation-services/$slug': {
      id: '/rehabilitation-services/$slug'
      path: '/$slug'
      fullPath: '/rehabilitation-services/$slug'
      preLoaderRoute: typeof RehabilitationServicesSlugRouteImport
      parentRoute: typeof RehabilitationServicesRoute
    }
    '/conditions/$slug': {
      id: '/conditions/$slug'
      path: '/$slug'
      fullPath: '/conditions/$slug'
      preLoaderRoute: typeof ConditionsSlugRouteImport
      parentRoute: typeof ConditionsRoute
    }
  }
}

interface ConditionsRouteChildren {
  ConditionsSlugRoute: typeof ConditionsSlugRoute
}

const ConditionsRouteChildren: ConditionsRouteChildren = {
  ConditionsSlugRoute: ConditionsSlugRoute,
}

const ConditionsRouteWithChildren = ConditionsRoute._addFileChildren(
  ConditionsRouteChildren,
)

interface RehabilitationServicesRouteChildren {
  RehabilitationServicesSlugRoute: typeof RehabilitationServicesSlugRoute
}

const RehabilitationServicesRouteChildren: RehabilitationServicesRouteChildren =
  {
    RehabilitationServicesSlugRoute: RehabilitationServicesSlugRoute,
  }

const RehabilitationServicesRouteWithChildren =
  RehabilitationServicesRoute._addFileChildren(
    RehabilitationServicesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConditionsRoute: ConditionsRouteWithChildren,
  ProgramsRoute: ProgramsRoute,
  RehabilitationServicesRoute: RehabilitationServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
